default_platform(:ios)
platform :ios do
  lane :beta do
    increment_build_number(xcodeproj: "armvp.xcodeproj")
    build_app(
      workspace: "armvp.xcworkspace",
      scheme: "armvp",
      export_method: "app-store"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
